name: '🔏 Yarn Lock Changes'
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: '🚚 Checkout'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: '🔏 Yarn Lock Changes'
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}