name: '🧪 Run Tests'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Testing on Node ${{ matrix.node }}
    steps:
    - name: '🚚 Checkout'
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: '🔧 Setup Node'
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: ${{ matrix.node }}
    - name: '📦️ Install dependencies'
      run: yarn
    - name: '🧪 Run Unit tests'
      run: yarn test
    - name: '⚗️ Run CI Classic test'
      uses: ./
      with:
        path: tests/ci/classic/yarn.lock
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: '⚗️ Run CI Berry v2 test'
      uses: ./
      with:
        path: tests/ci/berry-v2/yarn.lock
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: '⚗️ Run CI Berry v3 test'
      uses: ./
      with:
        path: tests/ci/berry-v3/yarn.lock
        token: ${{ secrets.GITHUB_TOKEN }}
